# Name of your application. Used to uniquely configure containers.
service: crawler-app

# Name of the container image.
image: motokiyaze/crawler

registry:
  username: motokiyaze # (Registry username)
  password:
  - KAMAL_REGISTRY_PASSWORD

# Deploy to these servers.
servers:
  web:
  - 178.156.193.140
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

  # Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
  # Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
  #
  # Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
  # proxy: false # Configure builder setup.

proxy:
  ssl: false
  # host: your-domain.com # Replace with your domain
  app_port: 8081
  host: digital-dreamscape.net # (Your domain cloudflare)
  healthcheck:
    path: /v1/health

builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

  # Inject ENV variables into containers (secrets come from .kamal/secrets).

env:
  clear:
    REDIS_ADDR: crawler-app-redis:6379
  secret:
  - SEO_API_KEY
  - KAMAL_REGISTRY_PASSWORD
  - REDIS_PASSWORD
  - APP_ENV

accessories:
  redis:
    image: redis:7-alpine
    host: 178.156.193.140
    port: "6379"
    directories:
    - data:/data
